[versions]
kotlin = "2.4.10"
ksp = "2.3.11"
kotlinx-rpc = "0.10.3"
jib = "3.4.5"
compose = "1.12.0-beta03"
compose-hot-reload = "1.0.0-rc02"
ktor = "3.3.0"
ktor-legacy = "2.3.12"
serialization = "1.9.0"
coroutines = "1.10.2"
collections-immutable = "0.4.0"
datetime = "0.7.1"
logback-server = "1.5.18"
logback-admin = "1.5.13"
junit = "6.0.0"
calltreevisualizer = "0.0.2-alpha02"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-cio-jvm = { module = "io.ktor:ktor-client-cio-jvm", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-logging-legacy = { module = "io.ktor:ktor-client-logging", version.ref = "ktor-legacy" }
ktor-server-netty-jvm = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

kotlinx-rpc-krpc-client = { module = "org.jetbrains.kotlinx:kotlinx-rpc-krpc-client", version.ref = "kotlinx-rpc" }
kotlinx-rpc-krpc-ktor-client = { module = "org.jetbrains.kotlinx:kotlinx-rpc-krpc-ktor-client", version.ref = "kotlinx-rpc" }
kotlinx-rpc-krpc-ktor-server = { module = "org.jetbrains.kotlinx:kotlinx-rpc-krpc-ktor-server", version.ref = "kotlinx-rpc" }
kotlinx-rpc-krpc-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-rpc-krpc-serialization-json", version.ref = "kotlinx-rpc" }
kotlinx-rpc-krpc-server = { module = "org.jetbrains.kotlinx:kotlinx-rpc-krpc-server", version.ref = "kotlinx-rpc" }

kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "collections-immutable" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
calltreevisualizer-tracked-flow = { module = "com.woutwerkman.calltreevisualizer:tracked-call-tree-as-flow", version.ref = "calltreevisualizer" }
calltreevisualizer-call-tree-ui = { module = "com.woutwerkman.calltreevisualizer:call-tree-ui", version.ref = "calltreevisualizer" }
calltreevisualizer-stack-tracking-core-api = { module = "com.woutwerkman.calltreevisualizer:stack-tracking-core-api", version.ref = "calltreevisualizer" }
calltreevisualizer-flow-context-agent-api = { module = "com.woutwerkman.calltreevisualizer:flow-context-agent-api", version.ref = "calltreevisualizer" }
calltreevisualizer-flow-context-agent = { module = "com.woutwerkman.calltreevisualizer:flow-context-agent", version.ref = "calltreevisualizer" }

compose-hot-reload-runtime-api = { module = "org.jetbrains.compose.hot-reload:hot-reload-runtime-api", version.ref = "compose-hot-reload" }
logback-classic-admin = { module = "ch.qos.logback:logback-classic", version.ref = "logback-admin" }
logback-classic-server = { module = "ch.qos.logback:logback-classic", version.ref = "logback-server" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlinx-rpc = { id = "org.jetbrains.kotlinx.rpc.plugin", version.ref = "kotlinx-rpc" }
jib = { id = "com.google.cloud.tools.jib", version.ref = "jib" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-hot-reload = { id = "org.jetbrains.compose.hot-reload", version.ref = "compose-hot-reload" }
calltreevisualizer = { id = "com.woutwerkman.calltreevisualizer", version.ref = "calltreevisualizer" }
